# Generated by Django 4.2.1 on 2023-07-06 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_employe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='employe',
            new_name='Employee',
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
